/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package grupo8.view;

import grupo8.persistencia.GerenciadorDados;
import grupo8.pessoas.Pessoa;
import grupo8.pessoas.PessoaFisica;
import grupo8.pessoas.PessoaJuridica;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carpi
 */
public class JDialogBuscaPessoa extends javax.swing.JDialog {

    /**
     * Creates new form JDialogBuscaPessoa
     */
    
    private Pessoa pessoaSelecionada = null;
    private ArrayList<Pessoa> listaPessoas;
    
    
    public JDialogBuscaPessoa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarDados();
        this.setLocationRelativeTo(parent);
    }
    
    public Pessoa getPessoaSelecionada() {
        return pessoaSelecionada;
    }

    private void carregarDados() {
            GerenciadorDados g = new GerenciadorDados();
            listaPessoas = g.carregarPessoas(); // Carrega a lista do arquivo

            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0); // Limpa a tabela

            for (grupo8.pessoas.Pessoa p : listaPessoas) {
                String nome = "";
                String documento = "";
                String tipo = "";

                // Verifica o tipo e extrai os dados específicos
                if (p instanceof grupo8.pessoas.PessoaFisica) {
                    grupo8.pessoas.PessoaFisica pf = (grupo8.pessoas.PessoaFisica) p;
                    nome = pf.getNome();
                    documento = pf.getCPF();
                    tipo = "Física";
                } else if (p instanceof grupo8.pessoas.PessoaJuridica) {
                    grupo8.pessoas.PessoaJuridica pj = (grupo8.pessoas.PessoaJuridica) p;
                    nome = pj.getNomeFantasia(); // Ou pj.getRazaoSocial() se preferir
                    documento = pj.getCnpj();
                    tipo = "Jurídica";
                }

                // Adiciona a linha com as 7 colunas na ordem exata do cabeçalho
                modelo.addRow(new Object[]{
                    listaPessoas.indexOf(p) + 1, // 1. ID (Usando índice + 1)
                    nome,                        // 2. Nome
                    documento,                   // 3. CPF ou CNPJ
                    p.getEndereco(),             // 4. Endereço (Comum a todos)
                    p.getTelefone1(),            // 5. Telefone (Comum a todos)
                    p.getEmail(),                // 6. Email (Comum a todos)
                    tipo                         // 7. Tipo Pessoa
                });
            }
        }

    // Evento do botão Selecionar e Duplo Clique
    private void confirmarSelecao() {
        int linha = jTable1.getSelectedRow();
        if (linha != -1) {
            this.pessoaSelecionada = listaPessoas.get(linha);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma pessoa!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonSelecionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonSelecionar.setText("SELECIONAR");
        ButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonSelecionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(ButtonSelecionar)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF/CNPJ", "Endereço", "Telefone", "Email", "Tipo Pessoa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSelecionarActionPerformed
        // TODO add your handling code here:
        confirmarSelecao();
    }//GEN-LAST:event_ButtonSelecionarActionPerformed
                                               

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        if (evt.getClickCount() == 2) confirmarSelecao();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogBuscaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogBuscaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogBuscaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogBuscaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogBuscaPessoa dialog = new JDialogBuscaPessoa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSelecionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
