/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package grupo8.view;

/**
 *
 * @author carpi
 */
public class JDialogPagamento extends javax.swing.JDialog {
    
    private boolean pagamentoRealizado = false;
    private double valorTotal;
    private double valorPagoNestaSessao = 0.0; // O quanto ele pagou AGORA
    private double valorFaltante;

    /**
     * Creates new form JDialogPagamento
     */
    public JDialogPagamento(java.awt.Frame parent, boolean modal, double valorTotal) {
    super(parent, modal);
        initComponents();
        this.valorFaltante = valorTotal; // Agora sim pegamos o valor que veio da tela de venda!
        // ---------------------
        
        this.setLocationRelativeTo(parent);
        
        // Configura interface
        TextFieldTotalPagar.setText(String.format("%.2f", valorFaltante));
        TextFieldTotalPagar.setEditable(false);
        TextFieldTroco.setEditable(false);
        
        // Adiciona evento de ENTER no campo de recebimento
        TextFieldRecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularTroco();
            }
        });
        
        TextFieldRecebido.requestFocus();
    }
    
    private void calcularTroco() {
        try {
            String texto = TextFieldRecebido.getText().replace(",", ".");
            if(texto.isEmpty()) return;
            
            double recebido = Double.parseDouble(texto);
            
            if (recebido >= valorFaltante) {
                double troco = recebido - valorFaltante;
                TextFieldTroco.setText(String.format("%.2f", troco));
            } else {
                TextFieldTroco.setText("0,00");
            }
        } catch (NumberFormatException e) {
            // Ignora
        }
    }
    
    public double getValorPago() {
        return valorPagoNestaSessao;
    }
    
    public boolean isPagamentoRealizado() {
        return pagamentoRealizado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldRecebido = new javax.swing.JTextField();
        TextFieldTotalPagar = new javax.swing.JTextField();
        TextFieldTroco = new javax.swing.JTextField();
        LabelTotalPagar = new javax.swing.JLabel();
        LabelRecebido = new javax.swing.JLabel();
        LabelTroco = new javax.swing.JLabel();
        ButtonFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelTotalPagar.setText("Total a Pagar:");

        LabelRecebido.setText("Valor Recebido:");

        LabelTroco.setText("Troco:");

        ButtonFinalizar.setText("FINALIZAR");
        ButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldTotalPagar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelTotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(58, 58, 58)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldRecebido)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelRecebido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(48, 48, 48)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelTroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(96, 96, 96))
                            .addComponent(TextFieldTroco)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(ButtonFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(122, 122, 122)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTotalPagar)
                    .addComponent(LabelRecebido)
                    .addComponent(LabelTroco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(ButtonFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFinalizarActionPerformed
        // TODO add your handling code here:
       try {
            calcularTroco(); // Garante calculo visual do troco no dialog
            
            String texto = TextFieldRecebido.getText().replace(",", ".");
            if (texto.isEmpty()) return;
            
            double recebido = Double.parseDouble(texto);
            
            // --- CORREÇÃO AQUI ---
            // Não importa se é maior, menor ou igual. 
            // Retornamos EXATAMENTE o que o cliente deu.
            this.valorPagoNestaSessao = recebido; 
            // ---------------------
            
            this.pagamentoRealizado = true;
            this.dispose(); 
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Valor inválido.");
        }
    }//GEN-LAST:event_ButtonFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogPagamento dialog = new JDialogPagamento(new javax.swing.JFrame(), true, 0.0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonFinalizar;
    private javax.swing.JLabel LabelRecebido;
    private javax.swing.JLabel LabelTotalPagar;
    private javax.swing.JLabel LabelTroco;
    private javax.swing.JTextField TextFieldRecebido;
    private javax.swing.JTextField TextFieldTotalPagar;
    private javax.swing.JTextField TextFieldTroco;
    // End of variables declaration//GEN-END:variables
}
