/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo8.view;

import grupo8.persistencia.GerenciadorDados;
import java.util.ArrayList;
import grupo8.produto.Produto;

/**
 *
 * @author carpi
 */

public class JFrameGestaoProdutos extends javax.swing.JFrame {

    /**
     * Creates new form JFrameGestaoProdutos
     */
    GerenciadorDados gerenciador = new GerenciadorDados();
    ArrayList<Produto> listaProdutos = new ArrayList<>();

    public JFrameGestaoProdutos() {
        initComponents();
        atualizarTabela();
    }

    private void atualizarTabela() {
        // 1. Busca do arquivo
        listaProdutos = gerenciador.carregarLista();

        // 2. Limpa a tabela visual
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TabelaProdutos.getModel();
        modelo.setRowCount(0);

        // 3. Preenche com os dados (Polimorfismo ajuda aqui!)
        for (Produto p : listaProdutos) {

            // --- TRATAMENTO DO FABRICANTE ---
            String fabricanteTexto = ""; // Começa vazio por padrão

            // Pergunta: "Você é um Instrumento?"
            if (p instanceof grupo8.produto.Instrumento) {
                // Sim! Então converte (cast) e pega o fabricante
                grupo8.produto.Instrumento inst = (grupo8.produto.Instrumento) p;
                fabricanteTexto = inst.getFabricante();
            } // Pergunta: "Ou será que você é um Acessório?"
            else if (p instanceof grupo8.produto.Acessorio) {
                grupo8.produto.Acessorio acess = (grupo8.produto.Acessorio) p;
                //fabricanteTexto = acess.getFabricante();
            }

            modelo.addRow(new Object[]{
                // Assumindo que você tem getters na classe Produto
                p.getIdProduto(),
                p.getCodigo(),
                p.getDescricao(),
                fabricanteTexto,
                p.getMarca(),
                p.getDataFabricacao(),
                p.getPaisFabricacao(),
                p.getMaterial(),
                p.getCor(),
                p.getPreco(),
                p.getPeso(),
                p.getQntEstoque()
            // ... outros campos
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Novo = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaProdutos = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Novo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Excluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Novo)
                    .addComponent(Editar)
                    .addComponent(Excluir)))
        );

        TabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Descrição", "Fabricante", "Marca", "Data Fabricação", "País Fabricação", "Material", "Cor", "Preço", "Peso", "Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        // 1. Cria a janela
        JDialogCadastroProdutos dialog = new JDialogCadastroProdutos(this, true);

        // 2. Abre a janela (O código PAUSA aqui até você fechar o cadastro)
        dialog.setVisible(true);

        // --- A MÁGICA É AQUI ---
        // 3. Assim que a janela fecha, a gente manda recarregar a tabela do arquivo
        atualizarTabela();
    }//GEN-LAST:event_NovoActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        
        // 1. Verifica seleção
        int linha = TabelaProdutos.getSelectedRow();
        if (linha == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um produto para editar.");
            return;
        }

        // 2. Pega o objeto REAL da lista na memória
        Produto produtoSelecionado = listaProdutos.get(linha);

        // 3. Abre a tela de cadastro
        JDialogCadastroProdutos dialog = new JDialogCadastroProdutos(this, true);

        // 4. Passa os dados para a tela preencher
        dialog.preencherDados(produtoSelecionado);

        // 5. Mostra a tela (O código PAUSA aqui esperando você salvar e fechar)
        dialog.setVisible(true);

        // 6. SALVAMENTO FINAL (O Pulo do Gato)
        // Como passamos o objeto por referência, o Dialog atualizou os dados dele na memória RAM.
        // Agora precisamos gravar a lista inteira (com o produto modificado) no arquivo.
        gerenciador.salvarLista(listaProdutos);

        // 7. Atualiza a tabela visual
        atualizarTabela();
    }//GEN-LAST:event_EditarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = TabelaProdutos.getSelectedRow();

        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, selecione um produto na tabela para excluir.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Para o código aqui
        }

        // 2. Pergunta se tem certeza (Confirmação)
        // Pega o nome do produto para mostrar na mensagem (Coluna 2 é o Nome/Descrição)
        String nomeProduto = TabelaProdutos.getValueAt(linhaSelecionada, 2).toString();

        int opcao = javax.swing.JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja excluir o produto:\n" + nomeProduto + "?",
                "Confirmar Exclusão",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        // 3. Se o usuário clicou em SIM
        if (opcao == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // A MÁGICA: Como sua tabela foi montada lendo a listaProdutos sequencialmente,
                // o índice da linha (0, 1, 2...) é IGUAL ao índice na ArrayList.

                // Remove da memória
                listaProdutos.remove(linhaSelecionada);

                // Salva a lista nova no arquivo (Sobrescreve o antigo)
                gerenciador.salvarLista(listaProdutos);

                // Atualiza a tela
                atualizarTabela();

                javax.swing.JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Erro ao excluir: " + e.getMessage(),
                        "Erro",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(JFrameGestaoProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(JFrameGestaoProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(JFrameGestaoProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(JFrameGestaoProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new JFrameGestaoProdutos().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Novo;
    private javax.swing.JTable TabelaProdutos;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
